### ISSUE TITLE
"Uncaught runtime errors" when logging in with OSM

### ISSUE THREAD

**Issue by mglsj** [hotosm/fAIr#254]
**Describe the bug**
```
ERROR
Objects are not valid as a React child (found: TypeError: Cannot read properties of undefined (reading 'access_token')). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (http://127.0.0.1:3000/static/js/bundle.js:51835:19)
    at updateSlot (http://127.0.0.1:3000/static/js/bundle.js:52084:11)
    at reconcileChildrenArray (http://127.0.0.1:3000/static/js/bundle.js:52198:26)
    at reconcileChildFibers (http://127.0.0.1:3000/static/js/bundle.js:52571:18)
    at reconcileChildren (http://127.0.0.1:3000/static/js/bundle.js:55086:32)
    at updateFunctionComponent (http://127.0.0.1:3000/static/js/bundle.js:55415:7)
    at beginWork (http://127.0.0.1:3000/static/js/bundle.js:56844:20)
    at HTMLUnknownElement.callCallback (http://127.0.0.1:3000/static/js/bundle.js:43873:18)
    at Object.invokeGuardedCallbackDev (http://127.0.0.1:3000/static/js/bundle.js:43917:20)
    at invokeGuardedCallback (http://127.0.0.1:3000/static/js/bundle.js:43972:35)
 ```

**To Reproduce**
1. Login with osm

**Screenshots**
![image](https://github.com/hotosm/fAIr/assets/73988826/5c1d839d-2c1a-42cc-bf76-8783db7706a1)

**Desktop (please complete the following information):**
 - OS: Windows 11, Ubuntu wsl

**Comment by kshitijrajsharma** [comment]
Thanks for the bug report , Can I ask to kindly mention where you are encountering this issue ?

**Comment by mglsj** [comment]
> Thanks for the bug report , Can I ask to kindly mention where you are encountering this issue ? 

Ahh sorry i forgot to mention. I was testing the dev build on docker. Did all the steps mentioned in the guide.
